version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      cargo-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: cargo
    directory: /clump-python
    schedule:
      interval: weekly
    groups:
      cargo-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: pip
    directory: /clump-python
    schedule:
      interval: weekly
    groups:
      pip-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor-patch:
        update-types: [minor, patch]
